
# baseURL = "https://example.com"
languageCode = "zh-CN"
title = "米司博客-世界上有10种人，一种懂二进制，一种不懂二进制"
theme = "cactus"
copyright = "Misitebao" # cactus will use title if copyright is not set
disqusShortname = "misitebao" # Used when comments is enabled. Cactus will use site title if not set
# googleAnalytics = "UA-1234-5"


# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "主页"
url = "/"
weight = 1

[[menu.main]]
name = "写作"
url = "/posts"
weight = 2

[[menu.main]]
name = "分类"
url = "/categories"
weight = 3

[[menu.main]]
name = "标签"
url = "/tags"
weight = 4

[[menu.main]]
name = "关于我"
url = "/about"
weight = 5

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]

  logo = "https://cdn.jsdelivr.net/gh/misitebao/CDN@master/gravatar.png" # logo
  colortheme = "white" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default

  # Home page settings
  description = "米司博客-世界上有10种人，一种懂二进制，一种不懂二进制"
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = true # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/gohugoio" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = false # default

  [params.comments]
    enabled = false # default
    engine = "disqus" # more supported engines will be added.

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/misitebao"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/company/github/"
  [[params.social]]
    name = "email"
    link = "example@example.com"  # no need for "mailto:" in the head

